# pylint: disable=missing-class-docstring, missing-module-docstring
# Generated by Django 4.2 on 2023-04-12 21:32

from django.db import migrations, models

EXAMPLE_DATA = """INSERT INTO public.user (nickname, birth_date) VALUES
    ('zigal0', '1999-11-30'),
    ('kiram', '2000-04-25'),
    ('0leg', '1999-07-13'),
    ('VladOS', '1999-01-11'),
    ('Alex', '1999-10-27');
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.TextField(unique=True)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.RunSQL(EXAMPLE_DATA)
    ]
