# Generated by Django 4.2 on 2023-04-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.TextField(unique=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
